livereload: true

collections:
  news:
    output: true

# defaults:
#   - scope:
#       path: ""
#       type: "news"
#     values:
#       layout: "news_list_of_each_year"

kramdown:
  hard_wrap: true
  html_to_native: true

plugins:
  - jekyll-breadcrumbs-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - gitpush.sh
  - publish.sh
  - server.sh
